import { DamageCategoryUnique, DamageType } from "../../module/system/damage/types.ts";
import { energyDamageTypes } from "./traits.ts";
declare const damageCategoriesUnique: Record<DamageCategoryUnique, string>;
declare const materialDamageEffects: {
    adamantine: string;
    "cold-iron": string;
    dawnsilver: string;
    duskwood: string;
    orichalcum: string;
    silver: string;
    "sisterstone-dusk": string;
    "sisterstone-scarlet": string;
    warpglass: string;
    abysium: string;
    djezet: string;
    inubrix: string;
    "keep-stone": string;
    noqual: string;
    peachwood: string;
    siccatite: string;
    "sovereign-steel": string;
};
declare const damageCategories: {
    energy: string;
    physical: string;
    adamantine: string;
    "cold-iron": string;
    dawnsilver: string;
    duskwood: string;
    orichalcum: string;
    silver: string;
    "sisterstone-dusk": string;
    "sisterstone-scarlet": string;
    warpglass: string;
    abysium: string;
    djezet: string;
    inubrix: string;
    "keep-stone": string;
    noqual: string;
    peachwood: string;
    siccatite: string;
    "sovereign-steel": string;
    persistent: string;
    precision: string;
    splash: string;
};
declare const physicalDamageTypes: {
    bleed: string;
    bludgeoning: string;
    piercing: string;
    slashing: string;
};
declare const damageTypes: Record<DamageType, string>;
declare const damageRollFlavors: Record<"poison" | "bludgeoning" | "piercing" | "slashing" | "bleed" | "vitality" | "void" | "acid" | "cold" | "electricity" | "fire" | "sonic" | "force" | "mental" | "spirit" | "untyped", string>;
export { damageCategories, damageCategoriesUnique, damageRollFlavors, damageTypes, energyDamageTypes, materialDamageEffects, physicalDamageTypes, };
