import { DamageCategoryUnique, DamageType } from "../../module/system/damage/types.ts";
declare const damageCategoriesUnique: Record<DamageCategoryUnique, string>;
declare const materialDamageEffects: Pick<Record<"adamantine" | "cold-iron" | "dawnsilver" | "duskwood" | "orichalcum" | "silver" | "sisterstone-dusk" | "sisterstone-scarlet" | "warpglass" | "abysium" | "djezet" | "dragonhide" | "grisantian-pelt" | "inubrix" | "keep-stone" | "noqual" | "peachwood" | "siccatite" | "sisterstone" | "sovereign-steel", string>, "adamantine" | "cold-iron" | "dawnsilver" | "duskwood" | "orichalcum" | "silver" | "sisterstone-dusk" | "sisterstone-scarlet" | "warpglass" | "abysium" | "djezet" | "inubrix" | "keep-stone" | "noqual" | "peachwood" | "siccatite" | "sovereign-steel">;
declare const damageCategories: {
    energy: string;
    physical: string;
    adamantine: string;
    "cold-iron": string;
    dawnsilver: string;
    duskwood: string;
    orichalcum: string;
    silver: string;
    "sisterstone-dusk": string;
    "sisterstone-scarlet": string;
    warpglass: string;
    abysium: string;
    djezet: string;
    inubrix: string;
    "keep-stone": string;
    noqual: string;
    peachwood: string;
    siccatite: string;
    "sovereign-steel": string;
    persistent: string;
    precision: string;
    splash: string;
};
declare const physicalDamageTypes: {
    bleed: string;
    bludgeoning: string;
    piercing: string;
    slashing: string;
};
declare const damageTypes: Record<DamageType, string>;
declare const damageRollFlavors: Record<"bludgeoning" | "piercing" | "slashing" | "bleed" | "vitality" | "void" | "acid" | "cold" | "electricity" | "fire" | "sonic" | "force" | "mental" | "poison" | "spirit" | "untyped", string>;
export { damageCategories, damageCategoriesUnique, damageRollFlavors, damageTypes, materialDamageEffects, physicalDamageTypes, };
